<?php 
/*
 Generated by Manuigniter v2.0 
 www.manuigniter.com
*/
 class Receipts_payment extends CI_Controller{
   function __construct()
   {
     parent::__construct();
     $this->load->model('Receipts_payment_model');
     $this->load->model('Customer_model');
     $this->load->model('Petrol_pumps_model');
     $this->load->model('Gate_entry_pass_model');
   } 
 /*
* Listing of receipts_payment
 */
public function index()
{
  try{
    $data['noof_page'] = 0;
    $data['receipts_payment'] = $this->Receipts_payment_model->get_all_receipts_payment();
    $data['_view'] = 'receipts_payment/index';
     // $this->load->view('layouts/main',$data);
    $this->load->view('receipts_payment/index', $data);
  } catch (Exception $ex) {
    throw new Exception('Receipts_payment Controller : Error in index function - ' . $ex);
  }  
}
 /*
  * Adding a new receipts_payment
  */
 function add()
 {  
  extract($_POST);
 // print_r($_POST);exit();
  try{
    $company_id = $this->session->userdata('company_id');
    $params = array(
     'date'=> $this->input->post('date'),
     'voucher_no'=> $this->input->post('voucher_no'),
     'payment_type'=> $this->input->post('payment_type'),
     'bank_id'=> $this->input->post('from_to_bank'),
     'user_type'=> $this->input->post('user_type'),
     'customer_id'=> $this->input->post('customer_id'),
     'supplier_id'=> $this->input->post('supplier_id'),
     'vehicle_id'=> $this->input->post('vehicle_id'),
     'supervisor_id'=> $this->input->post('supervisor_id'),
     'pump_id'=> $this->input->post('pump_id'),
     'remark'=> $this->input->post('remark'),
     'amount'=> $this->input->post('amount'),
     'blty_or_dc_no'=> $this->input->post('blty_or_dc_no'),
     'company_id'=> $company_id,
     'created_at'=> date('Y-m-d H:m:s'),
      // 'updated_at'=> $this->input->post('updated_at'),
   );
    $this->load->library('upload');
    $this->load->library('form_validation');
    if(isset($_POST) && count($_POST) > 0)     
    {  
      $id= $this->Receipts_payment_model->add_receipts_payment($params);
      $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully added.</div>');
      redirect('receipts_payment/index');
    }
    else
    { 
     $data['_view'] = 'receipts_payment/add';
     $data['receipts_payment'] = $this->db->query("select * from receipts_payment ORDER BY `receipts_payment`.`id` DESC")->row_array();

     $data['supplier'] = $this->db->query("select * from suppliers")->result_array();
     $data['superviser'] = $this->db->query("select * from user where user_type='2'")->result_array();
     $data['customer'] = $this->Customer_model->get_all_customer();
     $data['petrol_pumps'] = $this->Petrol_pumps_model->get_all_petrol_pumps();
     $data['truck_number'] = $this->Gate_entry_pass_model->get_truck_number();

     $data['bank'] = $this->db->get('bank')->result_array();
     $this->load->view('receipts_payment/add',$data);
   }
 } catch (Exception $ex) {
  throw new Exception('Receipts_payment Controller : Error in add function - ' . $ex);
}  
}  
  /*
  * Editing a receipts_payment
 */
  public function edit($id)
  {   
    try{
     $data['receipts_payment'] = $this->Receipts_payment_model->get_receipts_payment($id);
     $this->load->library('upload');
     $this->load->library('form_validation');
     if(isset($data['receipts_payment']['id']))
     {
      $params = array(
       'date'=> $this->input->post('date'),
       'voucher_no'=> $this->input->post('voucher_no'),
       'payment_type'=> $this->input->post('payment_type'),
       'bank_id'=> $this->input->post('bank_id'),
       'user_type'=> $this->input->post('user_type'),
       'customer_id'=> $this->input->post('customer_id'),
       'supplier_id'=> $this->input->post('supplier_id'),
       'vehicle_id'=> $this->input->post('vehicle_id'),
       'supervisor_id'=> $this->input->post('supervisor_id'),
       'pump_id'=> $this->input->post('pump_id'),
       'remark'=> $this->input->post('remark'),
       'amount'=> $this->input->post('amount'),
       'blty_or_dc_no'=> $this->input->post('blty_or_dc_no'),
       'company_id'=> $this->input->post('company_id'),
       'created_at'=> $this->input->post('created_at'),
       'updated_at'=> $this->input->post('updated_at'),
     );
      if(isset($_POST) && count($_POST) > 0)     
      {  
       $this->Receipts_payment_model->update_receipts_payment($id,$params);
       $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully updated.</div>');
       redirect('receipts_payment/index');
     }
     else
     {
      $data['_view'] = 'receipts_payment/edit';
      $this->load->view('layouts/main',$data);
    }
  }
  else
    show_error('The receipts_payment you are trying to edit does not exist.');
} catch (Exception $ex) {
  throw new Exception('Receipts_payment Controller : Error in edit function - ' . $ex);
}  
} 
/*
  * Deleting receipts_payment
  */
function remove($id)
{
  try{
    $receipts_payment = $this->Receipts_payment_model->get_receipts_payment($id);
  // check if the receipts_payment exists before trying to delete it
    if(isset($receipts_payment['id']))
    {
     $this->Receipts_payment_model->delete_receipts_payment($id);
     $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully Removed.</div>');
     redirect('receipts_payment/index');
   }
   else
     show_error('The receipts_payment you are trying to delete does not exist.');
 } catch (Exception $ex) {
  throw new Exception('Receipts_payment Controller : Error in remove function - ' . $ex);
}  
}
  /*
  * View more a receipts_payment
 */
  public function view_more($id)
  {   
    try{
     $data['receipts_payment'] = $this->Receipts_payment_model->get_receipts_payment($id);
     if(isset($data['receipts_payment']['id']))
     {
      $data['_view'] = 'receipts_payment/view_more';
      $this->load->view('receipts_payment/view_more',$data);
    }
    else
      show_error('The receipts_payment you are trying to view more does not exist.');
  } catch (Exception $ex) {
    throw new Exception('Receipts_payment Controller : Error in View more function - ' . $ex);
  }  
} 
 /*
* Listing of receipts_payment
 */
public function search_by_clm()
{
  $column_name= $this->input->post('column_name');
  $value_id= $this->input->post('value_id');
  $data['noof_page'] = 0;
  $params = array();
  $data['receipts_payment'] = $this->Receipts_payment_model->get_all_receipts_payment_by_cat($column_name,$value_id);
  $data['_view'] = 'receipts_payment/index';
  $this->load->view('layouts/main',$data);
}
 /*
* get search values by column- receipts_payment
 */
public function get_search_values_by_clm()
{
  $clm_name= $this->input->post('clm_name');
  $value= $this->input->post('value');
  $id= $this->input->post('id');
  $params = array(
    $clm_name=>$value,
  );
  $this->Receipts_payment_model->update_receipts_payment($id,$params);
  $data['noof_page'] = 0;
  $data['receipts_payment'] = $this->Receipts_payment_model->get_all_receipts_payment();
  $this->load->view('receipts_payment/index',$data);
}
}
