<?php 
/*
 Generated by Manuigniter v2.0 
 www.manuigniter.com
*/
class Suppliers extends CI_Controller{
 function __construct()
 {
       parent::__construct();
      $this->load->model('Suppliers_model');
      $this->load->model('State_model');
       $user_data = $this->session->userdata();
         if($user_data['username'] == ''){
          redirect('logout');
        }
 } 
 /*
* Listing of suppliers
 */
public function index()
{
  try{
      $data['noof_page'] = 0;
     $data['suppliers'] = $this->Suppliers_model->get_all_suppliers();
      $data['_view'] = 'suppliers/index';
      $this->load->view('suppliers/index',$data);
    } catch (Exception $ex) {
      throw new Exception('Suppliers Controller : Error in index function - ' . $ex);
  }  
}
 /*
  * Adding a new suppliers
  */
 function add()
 {  
try{
      $params = array(
       'company_name'=> $this->input->post('company_name'),
       'address'=> $this->input->post('address'),
       'state_id'=> $this->input->post('state'),
       'phone'=> $this->input->post('phone'),
       'contact_person_name'=> $this->input->post('contact_person_name'),
       'contact_person_number'=> $this->input->post('contact_person_number'),
       'email'=> $this->input->post('email'),
       'gsts_no'=> $this->input->post('gstn_uin'),
       'opening_balance'=> $this->input->post('opening_balance'),
       'cr_dr'=> 'cr',
       'isActive'=> 'Y',
       'company_id'=> '1',
        ///'created_at'=> $this->input->post('created_at'),
        'created_at'=> date('Y-m-d H:m:s'),
        );
       $this->load->library('upload');
       $this->load->library('form_validation');
       if(isset($_POST) && count($_POST) > 0)     
        {  
            $id= $this->Suppliers_model->add_suppliers($params);
             $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully added.</div>');
              redirect('suppliers/index');
        }
        else
        { 
           $data['_view'] = 'suppliers/add';
            $data['state'] = $this->State_model->get_all_state();
            $this->load->view('suppliers/add',$data);
        }
  } catch (Exception $ex) {
    throw new Exception('Suppliers Controller : Error in add function - ' . $ex);
  }  
 }  
  /*
  * Editing a suppliers
 */
 public function edit($id)
 {   
  try{
   $data['suppliers'] = $this->Suppliers_model->get_suppliers($id);
       $this->load->library('upload');
       $this->load->library('form_validation');
     if(isset($data['suppliers']['id']))
      {
        $params = array(
           'company_name'=> $this->input->post('company_name'),
           'address'=> $this->input->post('address'),
           'state_id'=> $this->input->post('state'),
           'phone'=> $this->input->post('phone'),
           'contact_person_name'=> $this->input->post('contact_person_name'),
           'contact_person_number'=> $this->input->post('contact_person_number'),
           'email'=> $this->input->post('email'),
           'gsts_no'=> $this->input->post('gstn_uin'),
           'opening_balance'=> $this->input->post('opening_balance'),
           'cr_dr'=> $this->input->post('cr_dr'),
           'cr_dr'=> 'cr',
            'isActive'=> 'Y',
            'company_id'=> '1',
        ///'created_at'=> $this->input->post('created_at'),
          'updated_at'=> date('Y-m-d H:m:s'),
        );
          if(isset($_POST) && count($_POST) > 0)     
           {  
           $this->Suppliers_model->update_suppliers($id,$params);
             $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully updated.</div>');
                redirect('suppliers/index');
           }
           else
          {
              $data['_view'] = 'suppliers/edit';
              $data['state'] = $this->State_model->get_all_state();
              $this->load->view('suppliers/edit',$data);
          }
  }
  else
  show_error('The suppliers you are trying to edit does not exist.');
  } catch (Exception $ex) {
    throw new Exception('Suppliers Controller : Error in edit function - ' . $ex);
  }  
} 
/*
  * Deleting suppliers
  */
  function remove($id)
   {
    try{
      $suppliers = $this->Suppliers_model->get_suppliers($id);
  // check if the suppliers exists before trying to delete it
       if(isset($suppliers['id']))
       {
         $this->Suppliers_model->delete_suppliers($id);
             $this->session->set_flashdata('alert_msg','<div class="alert alert-success text-center">Succesfully Removed.</div>');
           redirect('suppliers/index');
       }
       else
       show_error('The suppliers you are trying to delete does not exist.');
  } catch (Exception $ex) {
    throw new Exception('Suppliers Controller : Error in remove function - ' . $ex);
  }  
  }
  /*
  * View more a suppliers
 */
 public function view_more($id)
 {   
try{
   $data['suppliers'] = $this->Suppliers_model->get_suppliers($id);
     if(isset($data['suppliers']['id']))
      {
              $data['_view'] = 'suppliers/view_more';
              $this->load->view('layouts/main',$data);
      }
      else
        show_error('The suppliers you are trying to view more does not exist.');
    } catch (Exception $ex) {
    throw new Exception('Suppliers Controller : Error in View more function - ' . $ex);
  }  
} 
 /*
* Listing of suppliers
 */
public function search_by_clm()
{
    $column_name= $this->input->post('column_name');
    $value_id= $this->input->post('value_id');
     $data['noof_page'] = 0;
     $params = array();
    $data['suppliers'] = $this->Suppliers_model->get_all_suppliers_by_cat($column_name,$value_id);
      $data['_view'] = 'suppliers/index';
      $this->load->view('layouts/main',$data);
}
 /*
* get search values by column- suppliers
 */
public function get_search_values_by_clm()
{
    $clm_name= $this->input->post('clm_name');
    $value= $this->input->post('value');
    $id= $this->input->post('id');
        $params = array(
        $clm_name=>$value,
        );
           $this->Suppliers_model->update_suppliers($id,$params);
   $data['noof_page'] = 0;
  $data['suppliers'] = $this->Suppliers_model->get_all_suppliers();
  $this->load->view('suppliers/index',$data);
}
 }
