<?php 
/*
   Generated by Manuigniter v2.0 
   www.manuigniter.com
*/
class Bagasse_sale_model extends CI_Model 
{ 
     function __construct()
      {
          parent::__construct();
      }
      /*
        * Get bagasse_sale by id 
      */ 
      function get_bagasse_sale($id)
      {
        try{
           return $this->db->get_where('bagasse_sale',array('id'=>$id))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Bagasse_sale_model Model : Error in get_bagasse_sale function - ' . $ex);
           }  
      }
      /*
        * Get bagasse_sale by  column name
      */ 
      function get_bagasse_salebyclm_name($clm_name,$clm_value)
      {
        try{
           return $this->db->get_where('bagasse_sale',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Bagasse_sale_model Madel : Error in get_bagasse_salebyclm_name function - ' . $ex);
           }  
      }
     /*
        * Get All bagasse_sale count 
      */ 
      function get_all_bagasse_sale_count()
      {
        try{
           $this->db->from('bagasse_sale');
           return $this->db->count_all_results();
           } catch (Exception $ex) {
             throw new Exception('Bagasse_sale_model model : Error in get_all_bagasse_sale_count function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join bagasse_salecount 
      */ 
      function get_all_with_asso_bagasse_sale()
      {
        try{
          $query = $this->db->get(); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('Bagasse_sale_model model : Error in get_all_with_asso_bagasse_sale function - ' . $ex);
           }  
      }
      /*
          * Get all bagasse_sale 
      */ 
      function get_all_bagasse_sale($params = array())
      {
        try{
              $this->db->order_by('id', 'desc');
              if(isset($params) && !empty($params)){
               $this->db->limit($params['limit'], $params['offset']);
              }
               return $this->db->get('bagasse_sale')->result_array();
           } catch (Exception $ex) {
             throw new Exception('Bagasse_sale_model model : Error in get_all_bagasse_sale function - ' . $ex);
           }  
      } 
      /*
         * function to add new bagasse_sale 
      */
      function add_bagasse_sale($params)
      {
        try{
          $this->db->insert('bagasse_sale',$params);
        return $this->db->insert_id();
           } catch (Exception $ex) {
             throw new Exception('Bagasse_sale_model model : Error in add_bagasse_sale function - ' . $ex);
           }  
      }
      /* 
          * function to update bagasse_sale 
      */
      function update_bagasse_sale($id,$params)
      {
        try{
            $this->db->where('id',$id);
        return $this->db->update('bagasse_sale',$params);
           } catch (Exception $ex) {
             throw new Exception('Bagasse_sale_model model : Error in update_bagasse_sale function - ' . $ex);
           }  
       }
     /* 
          * function to delete bagasse_sale 
      */
       function delete_bagasse_sale($id)
       {
        try{
             return $this->db->delete('bagasse_sale',array('id'=>$id));
           } catch (Exception $ex) {
             throw new Exception('Bagasse_sale_model model : Error in delete_bagasse_sale function - ' . $ex);
           }  
       }
      /*
        * Get bagasse_sale by  column name where not in particular id
      */ 
      function get_bagasse_salebyclm_name_not_id($clm_name,$clm_value,$where_cond)
      {
        try{
            $this->db->where('id!=', $where_cond);
           return $this->db->get_where('bagasse_sale',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Bagasse_sale_model model : Error in get_bagasse_salebyclm_name_not_id function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join bagasse_salecount 
      */ 
      function get_all_with_asso_bagasse_sale_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
          $query = $this->db->get(); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('Bagasse_sale_model model : Error in get_all_with_asso_bagasse_sale_by_cat function - ' . $ex);
           }  
      }
      /*
          * Get all bagasse_sale_by_cat 
      */ 
      function get_all_bagasse_sale_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
              $this->db->order_by('id', 'desc');
              $this->db->where($column_name, $value_id);
              if(isset($params) && !empty($params)){
               $this->db->limit($params['limit'], $params['offset']);
              }
               return $this->db->get('bagasse_sale')->result_array();
           } catch (Exception $ex) {
             throw new Exception('Bagasse_sale_model model : Error in get_all_bagasse_sale_by_cat function - ' . $ex);
           }  
      } 
 }
