<?php 
/*
   Generated by Manuigniter v2.0 
   www.manuigniter.com
*/
class Material_model extends CI_Model 
{ 
     function __construct()
      {
          parent::__construct();
      }
      /*
        * Get material by id 
      */ 
      function get_material($id)
      {
        try{
           return $this->db->get_where('material',array('id'=>$id))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Material_model Model : Error in get_material function - ' . $ex);
           }  
      }
      /*
        * Get material by  column name
      */ 
      function get_materialbyclm_name($clm_name,$clm_value)
      {
        try{
           return $this->db->get_where('material',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Material_model Madel : Error in get_materialbyclm_name function - ' . $ex);
           }  
      }
      function getmaterial($postData = null){
        $response = array();

    ## Read value
    $draw = $postData['draw'];
    $start = $postData['start'];
    $rowperpage = $postData['length']; // Rows display per page
    $columnIndex = $postData['order'][0]['column']; // Column index
    $columnName = $postData['columns'][$columnIndex]['data']; // Column name
    $columnSortOrder = $postData['order'][0]['dir']; // asc or desc
    $searchValue = $postData['search']['value']; // Search value

    ## Search
    $searchQuery = "";
    if ($searchValue != '') {
      $searchQuery = " (code like '%" . $searchValue . "%' or name like '%" . $searchValue . "%') ";
    }

    ## Total number of records without filtering
    $this->db->select('count(*) as allcount');
    $records = $this->db->get('material')->result();
    $totalRecords = $records[0]->allcount;

    ## Total number of record with filtering
    $this->db->select('count(*) as allcount');
    if ($searchQuery != '') {
      $this->db->where($searchQuery);
    }

    $records = $this->db->get('material')->result();
    $totalRecordwithFilter = $records[0]->allcount;

    $this->db->select('*');
    if ($searchQuery != '') {
      $this->db->where($searchQuery);
    }

    $this->db->order_by($columnName, $columnSortOrder);
    $this->db->limit($rowperpage, $start);
    $records = $this->db->get('material')->result();

    $data = array();

    foreach ($records as $record) {
      $href="material/edit/".$record->id;
      $href1="material/remove/".$record->id;
      $data[] = array(
        "id" => $record->id,
        "code" => $record->code,
        "name" => $record->name,
        "href" => $record->id="<a href='$href' class='btn btn-info btn-xs'> <span class='fa fa-pencil'></span> Edit</a>
            ",
        
      );
    }

    ## Response
    $response = array(
      "draw" => intval($draw),
      "iTotalRecords" => $totalRecords,
      "iTotalDisplayRecords" => $totalRecordwithFilter,
      "aaData" => $data,
    );

    return $response;
  }

     
     /*
        * Get All material count 
      */ 
      function get_all_material_count()
      {
        try{
           $this->db->from('material');
           return $this->db->count_all_results();
           } catch (Exception $ex) {
             throw new Exception('Material_model model : Error in get_all_material_count function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join materialcount 
      */ 
      function get_all_with_asso_material()
      {
        try{
          $query = $this->db->get(); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('Material_model model : Error in get_all_with_asso_material function - ' . $ex);
           }  
      }
      /*
          * Get all material 
      */ 
      function get_all_material($params = array())
      {
        try{
              $this->db->order_by('id', 'desc');
              if(isset($params) && !empty($params)){
               $this->db->limit($params['limit'], $params['offset']);
              }
               return $this->db->get('material')->result_array();
           } catch (Exception $ex) {
             throw new Exception('Material_model model : Error in get_all_material function - ' . $ex);
           }  
      } 
      /*
         * function to add new material 
      */
      function add_material($params)
      {
        try{
          $this->db->insert('material',$params);
        return $this->db->insert_id();
           } catch (Exception $ex) {
             throw new Exception('Material_model model : Error in add_material function - ' . $ex);
           }  
      }
      /* 
          * function to update material 
      */
      function update_material($id,$params)
      {
        try{
            $this->db->where('id',$id);
        return $this->db->update('material',$params);
           } catch (Exception $ex) {
             throw new Exception('Material_model model : Error in update_material function - ' . $ex);
           }  
       }
     /* 
          * function to delete material 
      */
       function delete_material($id)
       {
        try{
             return $this->db->delete('material',array('id'=>$id));
           } catch (Exception $ex) {
             throw new Exception('Material_model model : Error in delete_material function - ' . $ex);
           }  
       }
      /*
        * Get material by  column name where not in particular id
      */ 
      function get_materialbyclm_name_not_id($clm_name,$clm_value,$where_cond)
      {
        try{
            $this->db->where('id!=', $where_cond);
           return $this->db->get_where('material',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Material_model model : Error in get_materialbyclm_name_not_id function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join materialcount 
      */ 
      function get_all_with_asso_material_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
          $query = $this->db->get(); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('Material_model model : Error in get_all_with_asso_material_by_cat function - ' . $ex);
           }  
      }
      /*
          * Get all material_by_cat 
      */ 
      function get_all_material_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
              $this->db->order_by('id', 'desc');
              $this->db->where($column_name, $value_id);
              if(isset($params) && !empty($params)){
               $this->db->limit($params['limit'], $params['offset']);
              }
               return $this->db->get('material')->result_array();
           } catch (Exception $ex) {
             throw new Exception('Material_model model : Error in get_all_material_by_cat function - ' . $ex);
           }  
      } 
 }
