<?php 
/*
   Generated by Manuigniter v2.0 
   www.manuigniter.com
*/
class Receipts_payment_model extends CI_Model 
{ 
     function __construct()
      {
          parent::__construct();
      }
      /*
        * Get receipts_payment by id 
      */ 
      function get_receipts_payment($id)
      {
        try{
           return $this->db->get_where('receipts_payment',array('id'=>$id))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Receipts_payment_model Model : Error in get_receipts_payment function - ' . $ex);
           }  
      }
      /*
        * Get receipts_payment by  column name
      */ 
      function get_receipts_paymentbyclm_name($clm_name,$clm_value)
      {
        try{
           return $this->db->get_where('receipts_payment',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Receipts_payment_model Madel : Error in get_receipts_paymentbyclm_name function - ' . $ex);
           }  
      }
     /*
        * Get All receipts_payment count 
      */ 
      function get_all_receipts_payment_count()
      {
        try{
           $this->db->from('receipts_payment');
           return $this->db->count_all_results();
           } catch (Exception $ex) {
             throw new Exception('Receipts_payment_model model : Error in get_all_receipts_payment_count function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join receipts_paymentcount 
      */ 
      function get_all_with_asso_receipts_payment()
      {
        try{
          $query = $this->db->get(); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('Receipts_payment_model model : Error in get_all_with_asso_receipts_payment function - ' . $ex);
           }  
      }
      /*
          * Get all receipts_payment 
      */ 
      function get_all_receipts_payment($params = array())
      {
        try{
              $this->db->order_by('id', 'desc');
              if(isset($params) && !empty($params)){
               $this->db->limit($params['limit'], $params['offset']);
              }
               return $this->db->get('receipts_payment')->result_array();
           } catch (Exception $ex) {
             throw new Exception('Receipts_payment_model model : Error in get_all_receipts_payment function - ' . $ex);
           }  
      } 
      /*
         * function to add new receipts_payment 
      */
      function add_receipts_payment($params)
      {
        try{
          $this->db->insert('receipts_payment',$params);
        return $this->db->insert_id();
           } catch (Exception $ex) {
             throw new Exception('Receipts_payment_model model : Error in add_receipts_payment function - ' . $ex);
           }  
      }
      /* 
          * function to update receipts_payment 
      */
      function update_receipts_payment($id,$params)
      {
        try{
            $this->db->where('id',$id);
        return $this->db->update('receipts_payment',$params);
           } catch (Exception $ex) {
             throw new Exception('Receipts_payment_model model : Error in update_receipts_payment function - ' . $ex);
           }  
       }
     /* 
          * function to delete receipts_payment 
      */
       function delete_receipts_payment($id)
       {
        try{
             return $this->db->delete('receipts_payment',array('id'=>$id));
           } catch (Exception $ex) {
             throw new Exception('Receipts_payment_model model : Error in delete_receipts_payment function - ' . $ex);
           }  
       }
      /*
        * Get receipts_payment by  column name where not in particular id
      */ 
      function get_receipts_paymentbyclm_name_not_id($clm_name,$clm_value,$where_cond)
      {
        try{
            $this->db->where('id!=', $where_cond);
           return $this->db->get_where('receipts_payment',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('Receipts_payment_model model : Error in get_receipts_paymentbyclm_name_not_id function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join receipts_paymentcount 
      */ 
      function get_all_with_asso_receipts_payment_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
          $query = $this->db->get(); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('Receipts_payment_model model : Error in get_all_with_asso_receipts_payment_by_cat function - ' . $ex);
           }  
      }
      /*
          * Get all receipts_payment_by_cat 
      */ 
      function get_all_receipts_payment_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
              $this->db->order_by('id', 'desc');
              $this->db->where($column_name, $value_id);
              if(isset($params) && !empty($params)){
               $this->db->limit($params['limit'], $params['offset']);
              }
               return $this->db->get('receipts_payment')->result_array();
           } catch (Exception $ex) {
             throw new Exception('Receipts_payment_model model : Error in get_all_receipts_payment_by_cat function - ' . $ex);
           }  
      } 
 }
