<?php 
/*
   Generated by Manuigniter v2.0 
   www.manuigniter.com
*/
class State_model extends CI_Model 
{ 
     function __construct()
      {
          parent::__construct();
      }
      /*
        * Get state by state_id 
      */ 
      function get_state($state_id)
      {
        try{
           return $this->db->get_where('state',array('state_id'=>$state_id))->row_array();
           } catch (Exception $ex) {
             throw new Exception('State_model Model : Error in get_state function - ' . $ex);
           }  
      }
      /*
        * Get state by  column name
      */ 
      function get_statebyclm_name($clm_name,$clm_value)
      {
        try{
           return $this->db->get_where('state',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('State_model Madel : Error in get_statebyclm_name function - ' . $ex);
           }  
      }
     /*
        * Get All state count 
      */ 
      function get_all_state_count()
      {
        try{
           $this->db->from('state');
           return $this->db->count_all_results();
           } catch (Exception $ex) {
             throw new Exception('State_model model : Error in get_all_state_count function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join statecount 
      */ 
      function get_all_with_asso_state()
      {
        try{
          $query = $this->db->get(); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('State_model model : Error in get_all_with_asso_state function - ' . $ex);
           }  
      }
      /*
          * Get all state 
      */ 
      function get_all_state($params = array())
      {
        try{
              $this->db->where('country_id', '101');
              $this->db->order_by('state_id', 'asc');
              if(isset($params) && !empty($params)){
               $this->db->limit($params['limit'], $params['offset']);
              }
               return $this->db->get('state')->result_array();
           } catch (Exception $ex) {
             throw new Exception('State_model model : Error in get_all_state function - ' . $ex);
           }  
      } 
      /*
         * function to add new state 
      */
      function add_state($params)
      {
        try{
          $this->db->insert('state',$params);
        return $this->db->insert_id();
           } catch (Exception $ex) {
             throw new Exception('State_model model : Error in add_state function - ' . $ex);
           }  
      }
      /* 
          * function to update state 
      */
      function update_state($state_id,$params)
      {
        try{
            $this->db->where('state_id',$state_id);
        return $this->db->update('state',$params);
           } catch (Exception $ex) {
             throw new Exception('State_model model : Error in update_state function - ' . $ex);
           }  
       }
     /* 
          * function to delete state 
      */
       function delete_state($state_id)
       {
        try{
             return $this->db->delete('state',array('state_id'=>$state_id));
           } catch (Exception $ex) {
             throw new Exception('State_model model : Error in delete_state function - ' . $ex);
           }  
       }
      /*
        * Get state by  column name where not in particular id
      */ 
      function get_statebyclm_name_not_id($clm_name,$clm_value,$where_cond)
      {
        try{
            $this->db->where('state_id!=', $where_cond);
           return $this->db->get_where('state',array($clm_name=>$clm_value))->row_array();
           } catch (Exception $ex) {
             throw new Exception('State_model model : Error in get_statebyclm_name_not_id function - ' . $ex);
           }  
      }
     /*
        * Get All with associated tables join statecount 
      */ 
      function get_all_with_asso_state_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
          $query = $this->db->get(); 
            if($query->num_rows() != 0){
               return $query->result_array();
            }else{
                return false;
            }
           } catch (Exception $ex) {
             throw new Exception('State_model model : Error in get_all_with_asso_state_by_cat function - ' . $ex);
           }  
      }
      /*
          * Get all state_by_cat 
      */ 
      function get_all_state_by_cat($column_name=null,$value_id=null,$params=array())
      {
        try{
              $this->db->order_by('state_id', 'desc');
              $this->db->where($column_name, $value_id);
              if(isset($params) && !empty($params)){
               $this->db->limit($params['limit'], $params['offset']);
              }
               return $this->db->get('state')->result_array();
           } catch (Exception $ex) {
             throw new Exception('State_model model : Error in get_all_state_by_cat function - ' . $ex);
           }  
      } 
 }
