<?php
/*
Generated by Manuigniter v2.0
www.manuigniter.com
 */
class Transporter_model extends CI_Model {
	function __construct() {
		parent::__construct();
	}
	/*
		        * Get transporter by id
	*/
	function get_transporter($id) {
		try {
			return $this->db->get_where('vehicle_owner', array('id' => $id))->row_array();
		} catch (Exception $ex) {
			throw new Exception('Transporter_model Model : Error in get_transporter function - ' . $ex);
		}
	}

	function transporterList($postData = null) {
		$response = array();

		$draw = $postData['draw'];
		$start = $postData['start'];
		$rowperpage = $postData['length']; // Rows display per page
		$columnIndex = $postData['order'][0]['column']; // Column index
		$columnName = $postData['columns'][$columnIndex]['data']; // Column name
		$columnSortOrder = $postData['order'][0]['dir']; // asc or desc
		$searchValue = $postData['search']['value']; // Search value

		## Search
		$searchQuery = "";
		if ($searchValue != '') {
			$searchQuery = " (owner_name like '%" . $searchValue . "%'  or address like '%" . $searchValue . "%' or contact_person_name like '%" . $searchValue . "%' or contact_person_number like '%" . $searchValue . "%' ) ";
		}

		## Total number of records without filtering
		$this->db->select('count(*) as allcount');
		$records = $this->db->get('vehicle_owner')->result();
		$totalRecords = $records[0]->allcount;

		## Total number of record with filtering
		$this->db->select('count(*) as allcount');
		if ($searchQuery != '') {
			$this->db->where($searchQuery);
		}

		$records = $this->db->get('vehicle_owner')->result();
		$totalRecordwithFilter = $records[0]->allcount;

		$this->db->select('*');
		if ($searchQuery != '') {
			$this->db->where($searchQuery);
		}

		$this->db->order_by($columnName, $columnSortOrder);
		$this->db->limit($rowperpage, $start);
		$records = $this->db->get('vehicle_owner')->result();

		$data = array();
		$i = '1';
		foreach ($records as $record) {

			$href = "transporter/edit/" . $record->id;
			$href1 = "locations/remove/" . $record->id;
			$data[] = array(
				"id" => $i++,
				"owner_name" => $record->owner_name,

				"address" => $record->address,
				"contact_person_name" => $record->contact_person_name,
				"contact_person_number" => $record->contact_person_number,

				"href" => $record->id = "<a href='$href' class='btn btn-info btn-xs'> <span class='fa fa-pencil'></span> Edit</a>",
				// <a id='is_remove' data-id='$record->id' value='$record->id' class='btn btn-danger btn-xs is_remove'> <span class='fa fa-trash'></span> Delete</a>
			);
		}

		## Response
		$response = array(
			"draw" => intval($draw),
			"iTotalRecords" => $totalRecords,
			"iTotalDisplayRecords" => $totalRecordwithFilter,
			"aaData" => $data,
		);

		return $response;
	}
	/*
		        * Get transporter by  column name
	*/
	function get_transporterbyclm_name($clm_name, $clm_value) {
		try {
			return $this->db->get_where('transporter', array($clm_name => $clm_value))->row_array();
		} catch (Exception $ex) {
			throw new Exception('Transporter_model Madel : Error in get_transporterbyclm_name function - ' . $ex);
		}
	}
	/*
		        * Get All transporter count
	*/
	function get_all_transporter_count() {
		try {
			$this->db->from('transporter');
			return $this->db->count_all_results();
		} catch (Exception $ex) {
			throw new Exception('Transporter_model model : Error in get_all_transporter_count function - ' . $ex);
		}
	}
	/*
		        * Get All with associated tables join transportercount
	*/
	function get_all_with_asso_transporter() {
		try {
			$query = $this->db->get();
			if ($query->num_rows() != 0) {
				return $query->result_array();
			} else {
				return false;
			}
		} catch (Exception $ex) {
			throw new Exception('Transporter_model model : Error in get_all_with_asso_transporter function - ' . $ex);
		}
	}
	/*
		          * Get all transporter
	*/
	function get_all_transporter($params = array()) {
		try {
			$this->db->order_by('id', 'desc');
			if (isset($params) && !empty($params)) {
				$this->db->limit($params['limit'], $params['offset']);
			}
			return $this->db->get('vehicle_owner')->result_array();
		} catch (Exception $ex) {
			throw new Exception('Transporter_model model : Error in get_all_transporter function - ' . $ex);
		}
	}
	/*
		         * function to add new transporter
	*/
	function add_transporter($params) {
		try {
			$this->db->insert('transporter', $params);
			return $this->db->insert_id();
		} catch (Exception $ex) {
			throw new Exception('Transporter_model model : Error in add_transporter function - ' . $ex);
		}
	}
	/*
		          * function to update transporter
	*/
	function update_transporter($id, $params) {
		try {
			$this->db->where('id', $id);
			return $this->db->update('transporter', $params);
		} catch (Exception $ex) {
			throw new Exception('Transporter_model model : Error in update_transporter function - ' . $ex);
		}
	}
	/*
		          * function to delete transporter
	*/
	function delete_transporter($id) {
		try {
			return $this->db->delete('transporter', array('id' => $id));
		} catch (Exception $ex) {
			throw new Exception('Transporter_model model : Error in delete_transporter function - ' . $ex);
		}
	}
	/*
		        * Get transporter by  column name where not in particular id
	*/
	function get_transporterbyclm_name_not_id($clm_name, $clm_value, $where_cond) {
		try {
			$this->db->where('id!=', $where_cond);
			return $this->db->get_where('transporter', array($clm_name => $clm_value))->row_array();
		} catch (Exception $ex) {
			throw new Exception('Transporter_model model : Error in get_transporterbyclm_name_not_id function - ' . $ex);
		}
	}
	/*
		        * Get All with associated tables join transportercount
	*/
	function get_all_with_asso_transporter_by_cat($column_name = null, $value_id = null, $params = array()) {
		try {
			$query = $this->db->get();
			if ($query->num_rows() != 0) {
				return $query->result_array();
			} else {
				return false;
			}
		} catch (Exception $ex) {
			throw new Exception('Transporter_model model : Error in get_all_with_asso_transporter_by_cat function - ' . $ex);
		}
	}
	/*
		          * Get all transporter_by_cat
	*/
	function get_all_transporter_by_cat($column_name = null, $value_id = null, $params = array()) {
		try {
			$this->db->order_by('id', 'desc');
			$this->db->where($column_name, $value_id);
			if (isset($params) && !empty($params)) {
				$this->db->limit($params['limit'], $params['offset']);
			}
			return $this->db->get('transporter')->result_array();
		} catch (Exception $ex) {
			throw new Exception('Transporter_model model : Error in get_all_transporter_by_cat function - ' . $ex);
		}
	}
}
