<?php
/*
Generated by Manuigniter v2.0
www.manuigniter.com
 */
class Transport_details_model extends CI_Model {
	function __construct() {
		parent::__construct();
	}
	/*
		        * Get transport_details by id
	*/
	function get_last_transport() {
		try {
			$this->db->order_by("id", "desc");
			return $this->db->get_where('transport_details')->row_array();
		} catch (Exception $ex) {
			throw new Exception('Transport_details_model Model : Error in get_transport_details function - ' . $ex);
		}
	}
	function get_transport_details($id) {
		try {
			$this->db->select('transport_details.*,labour.name,vehicle.vehicle_owner_id');
			$this->db->join('labour', 'labour.id = transport_details.loading_id');
			//	$this->db->join('labour as l', 'l.id = transport_details.unloading_id');
			$this->db->join('vehicle', 'vehicle.id = transport_details.vehicle_id');
			return $this->db->get_where('transport_details', array('transport_details.id' => $id))->row_array();
		} catch (Exception $ex) {
			throw new Exception('Transport_details_model Model : Error in get_transport_details function - ' . $ex);
		}
	}
	/*
		        * Get transport_details by  column name
	*/
	function get_transport_detailsbyclm_name($clm_name, $clm_value) {
		try {
			return $this->db->get_where('transport_details', array($clm_name => $clm_value))->row_array();
		} catch (Exception $ex) {
			throw new Exception('Transport_details_model Madel : Error in get_transport_detailsbyclm_name function - ' . $ex);
		}
	}
	/*
		        * Get All transport_details count
	*/
	function get_all_transport_details_count() {
		try {
			$this->db->from('transport_details');
			return $this->db->count_all_results();
		} catch (Exception $ex) {
			throw new Exception('Transport_details_model model : Error in get_all_transport_details_count function - ' . $ex);
		}
	}
	/*
		        * Get All with associated tables join transport_detailscount
	*/
	function get_all_with_asso_transport_details() {
		try {
			$query = $this->db->get();
			if ($query->num_rows() != 0) {
				return $query->result_array();
			} else {
				return false;
			}
		} catch (Exception $ex) {
			throw new Exception('Transport_details_model model : Error in get_all_with_asso_transport_details function - ' . $ex);
		}
	}
	/*
		          * Get all transport_details
	*/
	function get_all_transport_details($params = array()) {
		try {

			$company_id = $this->session->userdata('company_id');
			$this->db->order_by('id', 'desc');
			if (isset($params) && !empty($params)) {
				$this->db->limit($params['limit'], $params['offset']);
			}
			$this->db->where('company_id', $company_id);
			return $this->db->get('transport_details')->result_array();
		} catch (Exception $ex) {
			throw new Exception('Transport_details_model model : Error in get_all_transport_details function - ' . $ex);
		}
	}

	function get_all_diesel_transaction($id) {

		try {
			$this->db->select('diesel_transaction.*,vehicle.vehicle_number,transport_details.driver_name');
			$this->db->join('transport_details', 'transport_details.id = diesel_transaction.transport_id');
//			$this->db->join('driver', 'driver.id = transport_details.driver_id');
			$this->db->join('vehicle', 'vehicle.id = transport_details.vehicle_id');

			return $this->db->get_where('diesel_transaction', array('diesel_transaction.transport_id' => $id))->result_array();

		} catch (Exception $ex) {
			throw new Exception('Transport_details_model model : Error in get_all_transport_details function - ' . $ex);
		}
	}
	/*
		         * function to add new transport_details
	*/
	function add_transport_details($params) {
		try {
			$this->db->insert('transport_details', $params);
			return $this->db->insert_id();
		} catch (Exception $ex) {
			throw new Exception('Transport_details_model model : Error in add_transport_details function - ' . $ex);
		}
	}
	/*
		          * function to update transport_details
	*/
	function update_transport_details($id, $params) {
		try {
			$this->db->where('id', $id);
			return $this->db->update('transport_details', $params);
		} catch (Exception $ex) {
			throw new Exception('Transport_details_model model : Error in update_transport_details function - ' . $ex);
		}
	}
	/*
		          * function to delete transport_details
	*/
	function delete_transport_details($id) {
		try {
			return $this->db->delete('transport_details', array('id' => $id));
		} catch (Exception $ex) {
			throw new Exception('Transport_details_model model : Error in delete_transport_details function - ' . $ex);
		}
	}
	/*
		        * Get transport_details by  column name where not in particular id
	*/
	function get_transport_detailsbyclm_name_not_id($clm_name, $clm_value, $where_cond) {
		try {
			$this->db->where('id!=', $where_cond);
			return $this->db->get_where('transport_details', array($clm_name => $clm_value))->row_array();
		} catch (Exception $ex) {
			throw new Exception('Transport_details_model model : Error in get_transport_detailsbyclm_name_not_id function - ' . $ex);
		}
	}
	/*
		        * Get All with associated tables join transport_detailscount
	*/
	function get_all_with_asso_transport_details_by_cat($column_name = null, $value_id = null, $params = array()) {
		try {
			$query = $this->db->get();
			if ($query->num_rows() != 0) {
				return $query->result_array();
			} else {
				return false;
			}
		} catch (Exception $ex) {
			throw new Exception('Transport_details_model model : Error in get_all_with_asso_transport_details_by_cat function - ' . $ex);
		}
	}
	/*
		          * Get all transport_details_by_cat
	*/
	function get_all_transport_details_by_cat($column_name = null, $value_id = null, $params = array()) {
		try {
			$this->db->order_by('id', 'desc');
			$this->db->where($column_name, $value_id);
			if (isset($params) && !empty($params)) {
				$this->db->limit($params['limit'], $params['offset']);
			}
			return $this->db->get('transport_details')->result_array();
		} catch (Exception $ex) {
			throw new Exception('Transport_details_model model : Error in get_all_transport_details_by_cat function - ' . $ex);
		}
	}
}
