<?php
/*
Generated by Manuigniter v2.0
www.manuigniter.com
 */
class User_model extends CI_Model {
	function __construct() {
		parent::__construct();
	}
	/*
		        * Get user by id
	*/
	function get_user($id) {
		try {
			return $this->db->get_where('user', array('id' => $id))->row_array();
		} catch (Exception $ex) {
			throw new Exception('User_model Model : Error in get_user function - ' . $ex);
		}
	}
	function get_login($username, $password) {
		try {
			return $this->db->select('user.*,user_roles.name as role')->join('user_roles', 'user_roles.id=user.user_type')->get_where('user', array('username' => $username, 'isActive' => 'Y', 'is_delete' => 'N', 'password' => base64_encode($password)))->row_array();
		} catch (Exception $ex) {
			throw new Exception('User_model Model : Error in get_user function - ' . $ex);
		}
	}
	/*
		        * Get user by  column name
	*/
	function get_userbyclm_name($clm_name, $clm_value) {
		try {
			return $this->db->get_where('user', array($clm_name => $clm_value))->row_array();
		} catch (Exception $ex) {
			throw new Exception('User_model Madel : Error in get_userbyclm_name function - ' . $ex);
		}
	}
	/*
		        * Get All user count
	*/
	function get_all_user_count() {
		try {
			$this->db->from('user');
			return $this->db->count_all_results();
		} catch (Exception $ex) {
			throw new Exception('User_model model : Error in get_all_user_count function - ' . $ex);
		}
	}
	/*
		        * Get All with associated tables join usercount
	*/
	function get_all_with_asso_user() {
		try {
			$query = $this->db->get();
			if ($query->num_rows() != 0) {
				return $query->result_array();
			} else {
				return false;
			}
		} catch (Exception $ex) {
			throw new Exception('User_model model : Error in get_all_with_asso_user function - ' . $ex);
		}
	}
	/*
		          * Get all user
	*/
	function get_all_user($params = array()) {
		try {
			$this->db->where('is_delete', 'N');
			$this->db->order_by('id', 'desc');
			if (isset($params) && !empty($params)) {
				$this->db->limit($params['limit'], $params['offset']);
			}
			return $this->db->get('user')->result_array();
		} catch (Exception $ex) {
			throw new Exception('User_model model : Error in get_all_user function - ' . $ex);
		}
	}

	function userList($postData = null) {
		$response = array();

		$draw = $postData['draw'];
		$start = $postData['start'];
		$rowperpage = $postData['length']; // Rows display per page
		$columnIndex = $postData['order'][0]['column']; // Column index
		$columnName = $postData['columns'][$columnIndex]['data']; // Column name
		$columnSortOrder = $postData['order'][0]['dir']; // asc or desc
		$searchValue = $postData['search']['value']; // Search value

		## Search
		$searchQuery = "";
		if ($searchValue != '') {
			$searchQuery = " (name like '%" . $searchValue . "%' or mobile_number like '%" . $searchValue . "%' or email like '%" . $searchValue . "%' or username like '%" . $searchValue . "%'  ) ";
		}

		## Total number of records without filtering
		$this->db->select('count(*) as allcount');
		$records = $this->db->get('user')->result();
		$totalRecords = $records[0]->allcount;

		## Total number of record with filtering
		$this->db->select('count(*) as allcount');
		if ($searchQuery != '') {
			$this->db->where($searchQuery);
		}

		$records = $this->db->get('user')->result();
		$totalRecordwithFilter = $records[0]->allcount;

		$this->db->select('*');
		if ($searchQuery != '') {
			$this->db->where($searchQuery);
		}

		$this->db->order_by($columnName, $columnSortOrder);
		$this->db->limit($rowperpage, $start);
		$records = $this->db->get('user')->result();

		$data = array();
		$i = '1';
		foreach ($records as $record) {
			$href = base_url() . "user/edit/" . $record->id;
			$href1 = "locations/remove/" . $record->id;

			$data[] = array(
				"id" => $i++,
				"name" => $record->name,
				"mobile_number" => $record->mobile_number,
				"email" => $record->email,
				"username" => $record->username,
				"user_type" => get_usertype($record->user_type),
				'location_id' => get_userlocation($record->location_id),

				"href" => $record->id = "<a href='$href' class='btn btn-info btn-xs'> <span class='fa fa-pencil'></span> Edit</a>
           ",
				// <a id='is_remove' data-id='$record->id' value='$record->id' class='btn btn-danger btn-xs is_remove'> <span class='fa fa-trash'></span> Delete</a>
			);
		}

		## Response
		$response = array(
			"draw" => intval($draw),
			"iTotalRecords" => $totalRecords,
			"iTotalDisplayRecords" => $totalRecordwithFilter,
			"aaData" => $data,
		);

		return $response;
	}

	function get_all_type($params = array()) {
		try {
			$this->db->order_by('id', 'desc');
			if (isset($params) && !empty($params)) {
				$this->db->limit($params['limit'], $params['offset']);
			}
			return $this->db->get('user_roles')->result_array();
		} catch (Exception $ex) {
			throw new Exception('User_model model : Error in get_all_user function - ' . $ex);
		}
	}
	/*
		         * function to add new user
	*/
	function add_user($params) {
		try {
			$this->db->insert('user', $params);
			return $this->db->insert_id();
		} catch (Exception $ex) {
			throw new Exception('User_model model : Error in add_user function - ' . $ex);
		}
	}
	/*
		          * function to update user
	*/
	function update_user($id, $params) {
		try {
			$this->db->where('id', $id);
			return $this->db->update('user', $params);
		} catch (Exception $ex) {
			throw new Exception('User_model model : Error in update_user function - ' . $ex);
		}
	}
	/*
		          * function to delete user
	*/
	function delete_user($id) {
		try {
			return $this->db->delete('user', array('id' => $id));
		} catch (Exception $ex) {
			throw new Exception('User_model model : Error in delete_user function - ' . $ex);
		}
	}
	/*
		        * Get user by  column name where not in particular id
	*/
	function get_userbyclm_name_not_id($clm_name, $clm_value, $where_cond) {
		try {
			$this->db->where('id!=', $where_cond);
			return $this->db->get_where('user', array($clm_name => $clm_value))->row_array();
		} catch (Exception $ex) {
			throw new Exception('User_model model : Error in get_userbyclm_name_not_id function - ' . $ex);
		}
	}
	/*
		        * Get All with associated tables join usercount
	*/
	function get_all_with_asso_user_by_cat($column_name = null, $value_id = null, $params = array()) {
		try {
			$query = $this->db->get();
			if ($query->num_rows() != 0) {
				return $query->result_array();
			} else {
				return false;
			}
		} catch (Exception $ex) {
			throw new Exception('User_model model : Error in get_all_with_asso_user_by_cat function - ' . $ex);
		}
	}
	/*
		          * Get all user_by_cat
	*/
	function get_all_user_by_cat($column_name = null, $value_id = null, $params = array()) {
		try {
			$this->db->order_by('id', 'desc');
			$this->db->where($column_name, $value_id);
			if (isset($params) && !empty($params)) {
				$this->db->limit($params['limit'], $params['offset']);
			}
			return $this->db->get('user')->result_array();
		} catch (Exception $ex) {
			throw new Exception('User_model model : Error in get_all_user_by_cat function - ' . $ex);
		}
	}
}
