<?php 
/*
    Generated by Manuigniter v2.0 
    www.manuigniter.com
*/
use Restserver\Libraries\REST_Controller;
defined('BASEPATH') OR exit('No direct script access allowed');
require APPPATH . '/libraries/REST_Controller.php';
require APPPATH . 'libraries/Format.php';
class Bank extends REST_Controller{
 function __construct()
 {
       parent::__construct();
      $this->load->model('Bank_model');
 } 
 /*
* Listing of bank
 */
public function get_all_post()
{
  try{
  $data['bank'] = $this->Bank_model->get_all_bank();
     if($data['bank'] && $data['bank']!=null){
       $bank_ar = array();
       foreach($data['bank'] as $b)
       {
       $b_ar = array();
       $b_ar['id'] = $b['id'];
       $b_ar['name'] = $b['name'];
       $b_ar['company_id'] = $b['company_id'];
       $b_ar['created_at'] = $b['created_at'];
       $b_ar['updated_at'] = $b['updated_at'];
       $bank_ar[] = $b_ar;
       }
       $response = array(
       'status' => 200,
       'message' => 'get all data Succesfully',
       'data' => $bank_ar,
       );
       $this->response($response, REST_Controller::HTTP_OK);
     }
     else{
       $response = array(
      'status' => 400,
      'message' => 'Detail is not found'
        );
       $this->response($response, REST_Controller::HTTP_OK); 
        }
       } catch (Exception $ex) {
             throw new Exception('Bank controller_name : Error in get_all_post function - ' . $ex);
        }  
}
 /*
  * Adding a new bank
  */
 function addnew_post()
 {  
  try{
      $params = array(
       'name'=> $this->input->post('name'),
       'company_id'=> $this->input->post('company_id'),
       'created_at'=> $this->input->post('created_at'),
       'updated_at'=> $this->input->post('updated_at'),
        );
       $this->load->library('upload');
       $this->load->library('form_validation');
       if(isset($_POST) && count($_POST) > 0)     
        {  
            $id= $this->Bank_model->add_bank($params);
   $data['bank'] = $this->Bank_model->get_bank($id);
           $response = array(
            'status' => 200,
            'message' => 'Succesfully Added',
            'data' => $data
             );
           $this->response($response, REST_Controller::HTTP_OK);
        }
        else
        { 
           $response = array(
            'status' => 400,
            'message' => 'Not Added try again',
            'data' => ''
             );
           $this->response($response, REST_Controller::HTTP_OK);
        }
       } catch (Exception $ex) {
             throw new Exception('Bank controller_name : Error in new bank function - ' . $ex);
       }  
 }  
  /*
  * Editing a bank
 */
  function edit_post($id)
 {   
  try{
   $data['bank'] = $this->Bank_model->get_bank($id);
       $this->load->library('upload');
       $this->load->library('form_validation');
     if(isset($data['bank']['id']))
      {
        $params = array(
           'name'=> $this->input->post('name'),
           'company_id'=> $this->input->post('company_id'),
           'created_at'=> $this->input->post('created_at'),
           'updated_at'=> $this->input->post('updated_at'),
        );
          if(isset($_POST) && count($_POST) > 0)     
           {  
           $this->Bank_model->update_bank($id,$params);
           $response = array(
            'status' => 200,
            'message' => 'Succesfully Updated',
            'data' => $id
             );
           $this->response($response, REST_Controller::HTTP_OK);
           }
           else
          {
           $response = array(
            'status' => 400,
            'message' => 'Not Updated Try again',
            'data' => $id
             );
           $this->response($response, REST_Controller::HTTP_OK);
          }
  }
       } catch (Exception $ex) {
             throw new Exception('Bank controller_name : Error in edit_post function - ' . $ex);
        }  
} 
/*
  * Deleting bank
  */
  function remove_post($id)
   {
  try{
      $bank = $this->Bank_model->get_bank($id);
  // check if the bank exists before trying to delete it
       if(isset($bank['id']))
       {
         $this->Bank_model->delete_bank($id);
           $response = array(
            'status' => 200,
            'message' => 'Succesfully Removed',
            'data' => $id
             );
           $this->response($response, REST_Controller::HTTP_OK);
       }
       else
           $response = array(
            'status' => 400,
            'message' => 'Not Updated Try again',
            'data' => $id
             );
           $this->response($response, REST_Controller::HTTP_OK);
       } catch (Exception $ex) {
             throw new Exception('Bank controller_name : Error in remove_post function - ' . $ex);
        }  
  }
 }
