<?php 
/*
    Generated by Manuigniter v2.0 
    www.manuigniter.com
*/
use Restserver\Libraries\REST_Controller;
defined('BASEPATH') OR exit('No direct script access allowed');
require APPPATH . '/libraries/REST_Controller.php';
require APPPATH . 'libraries/Format.php';
class Payment_vouchers extends REST_Controller{
 function __construct()
 {
       parent::__construct();
      $this->load->model('Payment_vouchers_model');
 } 
 /*
* Listing of payment_vouchers
 */
public function get_all_post()
{
  try{
  $data['payment_vouchers'] = $this->Payment_vouchers_model->get_all_payment_vouchers();
     if($data['payment_vouchers'] && $data['payment_vouchers']!=null){
       $payment_vouchers_ar = array();
       foreach($data['payment_vouchers'] as $p)
       {
       $p_ar = array();
       $p_ar['id'] = $p['id'];
       $p_ar['date'] = $p['date'];
       $p_ar['vahicle_id'] = $p['vahicle_id'];
       $p_ar['bilty_no'] = $p['bilty_no'];
       $p_ar['amount'] = $p['amount'];
       $p_ar['supply_form'] = $p['supply_form'];
       $p_ar['name'] = $p['name'];
       $p_ar['ac_number'] = $p['ac_number'];
       $p_ar['bank_name'] = $p['bank_name'];
       $p_ar['branch'] = $p['branch'];
       $p_ar['ifsc_code'] = $p['ifsc_code'];
       $p_ar['added_by'] = $p['added_by'];
       $p_ar['company_id'] = $p['company_id'];
       $p_ar['created_at'] = $p['created_at'];
       $p_ar['updated_at'] = $p['updated_at'];
       $payment_vouchers_ar[] = $p_ar;
       }
       $response = array(
       'status' => 200,
       'message' => 'get all data Succesfully',
       'data' => $payment_vouchers_ar,
       );
       $this->response($response, REST_Controller::HTTP_OK);
     }
     else{
       $response = array(
      'status' => 400,
      'message' => 'Detail is not found'
        );
       $this->response($response, REST_Controller::HTTP_OK); 
        }
       } catch (Exception $ex) {
             throw new Exception('Payment_vouchers controller_name : Error in get_all_post function - ' . $ex);
        }  
}
 /*
  * Adding a new payment_vouchers
  */
 function addnew_post()
 {  
  try{
      $params = array(
       'date'=> $this->input->post('date'),
       'vahicle_id'=> $this->input->post('vahicle_id'),
       'bilty_no'=> $this->input->post('bilty_no'),
       'amount'=> $this->input->post('amount'),
       'supply_form'=> $this->input->post('supply_form'),
       'name'=> $this->input->post('name'),
       'ac_number'=> $this->input->post('ac_number'),
       'bank_name'=> $this->input->post('bank_name'),
       'branch'=> $this->input->post('branch'),
       'ifsc_code'=> $this->input->post('ifsc_code'),
       'added_by'=> $this->input->post('added_by'),
       'company_id'=> $this->input->post('company_id'),
       'created_at'=> $this->input->post('created_at'),
       'updated_at'=> $this->input->post('updated_at'),
        );
       $this->load->library('upload');
       $this->load->library('form_validation');
       if(isset($_POST) && count($_POST) > 0)     
        {  
            $id= $this->Payment_vouchers_model->add_payment_vouchers($params);
   $data['payment_vouchers'] = $this->Payment_vouchers_model->get_payment_vouchers($id);
           $response = array(
            'status' => 200,
            'message' => 'Succesfully Added',
            'data' => $data
             );
           $this->response($response, REST_Controller::HTTP_OK);
        }
        else
        { 
           $response = array(
            'status' => 400,
            'message' => 'Not Added try again',
            'data' => ''
             );
           $this->response($response, REST_Controller::HTTP_OK);
        }
       } catch (Exception $ex) {
             throw new Exception('Payment_vouchers controller_name : Error in new payment_vouchers function - ' . $ex);
       }  
 }  
  /*
  * Editing a payment_vouchers
 */
  function edit_post($id)
 {   
  try{
   $data['payment_vouchers'] = $this->Payment_vouchers_model->get_payment_vouchers($id);
       $this->load->library('upload');
       $this->load->library('form_validation');
     if(isset($data['payment_vouchers']['id']))
      {
        $params = array(
           'date'=> $this->input->post('date'),
           'vahicle_id'=> $this->input->post('vahicle_id'),
           'bilty_no'=> $this->input->post('bilty_no'),
           'amount'=> $this->input->post('amount'),
           'supply_form'=> $this->input->post('supply_form'),
           'name'=> $this->input->post('name'),
           'ac_number'=> $this->input->post('ac_number'),
           'bank_name'=> $this->input->post('bank_name'),
           'branch'=> $this->input->post('branch'),
           'ifsc_code'=> $this->input->post('ifsc_code'),
           'added_by'=> $this->input->post('added_by'),
           'company_id'=> $this->input->post('company_id'),
           'created_at'=> $this->input->post('created_at'),
           'updated_at'=> $this->input->post('updated_at'),
        );
          if(isset($_POST) && count($_POST) > 0)     
           {  
           $this->Payment_vouchers_model->update_payment_vouchers($id,$params);
           $response = array(
            'status' => 200,
            'message' => 'Succesfully Updated',
            'data' => $id
             );
           $this->response($response, REST_Controller::HTTP_OK);
           }
           else
          {
           $response = array(
            'status' => 400,
            'message' => 'Not Updated Try again',
            'data' => $id
             );
           $this->response($response, REST_Controller::HTTP_OK);
          }
  }
       } catch (Exception $ex) {
             throw new Exception('Payment_vouchers controller_name : Error in edit_post function - ' . $ex);
        }  
} 
/*
  * Deleting payment_vouchers
  */
  function remove_post($id)
   {
  try{
      $payment_vouchers = $this->Payment_vouchers_model->get_payment_vouchers($id);
  // check if the payment_vouchers exists before trying to delete it
       if(isset($payment_vouchers['id']))
       {
         $this->Payment_vouchers_model->delete_payment_vouchers($id);
           $response = array(
            'status' => 200,
            'message' => 'Succesfully Removed',
            'data' => $id
             );
           $this->response($response, REST_Controller::HTTP_OK);
       }
       else
           $response = array(
            'status' => 400,
            'message' => 'Not Updated Try again',
            'data' => $id
             );
           $this->response($response, REST_Controller::HTTP_OK);
       } catch (Exception $ex) {
             throw new Exception('Payment_vouchers controller_name : Error in remove_post function - ' . $ex);
        }  
  }
 }
