<?php 
/*
    Generated by Manuigniter v2.0 
    www.manuigniter.com
*/
use Restserver\Libraries\REST_Controller;
defined('BASEPATH') OR exit('No direct script access allowed');
require APPPATH . '/libraries/REST_Controller.php';
require APPPATH . 'libraries/Format.php';
class Sales_item extends REST_Controller{
 function __construct()
 {
       parent::__construct();
      $this->load->model('Sales_item_model');
 } 
 /*
* Listing of sales_item
 */
public function get_all_post()
{
  try{
  $data['sales_item'] = $this->Sales_item_model->get_all_sales_item();
     if($data['sales_item'] && $data['sales_item']!=null){
       $sales_item_ar = array();
       foreach($data['sales_item'] as $s)
       {
       $s_ar = array();
       $s_ar['id'] = $s['id'];
       $s_ar['sale_id'] = $s['sale_id'];
       $s_ar['item_id'] = $s['item_id'];
       $s_ar['unit_id'] = $s['unit_id'];
       $s_ar['total_cost'] = $s['total_cost'];
       $s_ar['status'] = $s['status'];
       $s_ar['weight'] = $s['weight'];
       $s_ar['rate'] = $s['rate'];
       $sales_item_ar[] = $s_ar;
       }
       $response = array(
       'status' => 200,
       'message' => 'get all data Succesfully',
       'data' => $sales_item_ar,
       );
       $this->response($response, REST_Controller::HTTP_OK);
     }
     else{
       $response = array(
      'status' => 400,
      'message' => 'Detail is not found'
        );
       $this->response($response, REST_Controller::HTTP_OK); 
        }
       } catch (Exception $ex) {
             throw new Exception('Sales_item controller_name : Error in get_all_post function - ' . $ex);
        }  
}
 /*
  * Adding a new sales_item
  */
 function addnew_post()
 {  
  try{
      $params = array(
       'sale_id'=> $this->input->post('sale_id'),
       'item_id'=> $this->input->post('item_id'),
       'unit_id'=> $this->input->post('unit_id'),
       'total_cost'=> $this->input->post('total_cost'),
       'status'=> $this->input->post('status'),
       'weight'=> $this->input->post('weight'),
       'rate'=> $this->input->post('rate'),
        );
       $this->load->library('upload');
       $this->load->library('form_validation');
       if(isset($_POST) && count($_POST) > 0)     
        {  
            $id= $this->Sales_item_model->add_sales_item($params);
   $data['sales_item'] = $this->Sales_item_model->get_sales_item($id);
           $response = array(
            'status' => 200,
            'message' => 'Succesfully Added',
            'data' => $data
             );
           $this->response($response, REST_Controller::HTTP_OK);
        }
        else
        { 
           $response = array(
            'status' => 400,
            'message' => 'Not Added try again',
            'data' => ''
             );
           $this->response($response, REST_Controller::HTTP_OK);
        }
       } catch (Exception $ex) {
             throw new Exception('Sales_item controller_name : Error in new sales_item function - ' . $ex);
       }  
 }  
  /*
  * Editing a sales_item
 */
  function edit_post($id)
 {   
  try{
   $data['sales_item'] = $this->Sales_item_model->get_sales_item($id);
       $this->load->library('upload');
       $this->load->library('form_validation');
     if(isset($data['sales_item']['id']))
      {
        $params = array(
           'sale_id'=> $this->input->post('sale_id'),
           'item_id'=> $this->input->post('item_id'),
           'unit_id'=> $this->input->post('unit_id'),
           'total_cost'=> $this->input->post('total_cost'),
           'status'=> $this->input->post('status'),
           'weight'=> $this->input->post('weight'),
           'rate'=> $this->input->post('rate'),
        );
          if(isset($_POST) && count($_POST) > 0)     
           {  
           $this->Sales_item_model->update_sales_item($id,$params);
           $response = array(
            'status' => 200,
            'message' => 'Succesfully Updated',
            'data' => $id
             );
           $this->response($response, REST_Controller::HTTP_OK);
           }
           else
          {
           $response = array(
            'status' => 400,
            'message' => 'Not Updated Try again',
            'data' => $id
             );
           $this->response($response, REST_Controller::HTTP_OK);
          }
  }
       } catch (Exception $ex) {
             throw new Exception('Sales_item controller_name : Error in edit_post function - ' . $ex);
        }  
} 
/*
  * Deleting sales_item
  */
  function remove_post($id)
   {
  try{
      $sales_item = $this->Sales_item_model->get_sales_item($id);
  // check if the sales_item exists before trying to delete it
       if(isset($sales_item['id']))
       {
         $this->Sales_item_model->delete_sales_item($id);
           $response = array(
            'status' => 200,
            'message' => 'Succesfully Removed',
            'data' => $id
             );
           $this->response($response, REST_Controller::HTTP_OK);
       }
       else
           $response = array(
            'status' => 400,
            'message' => 'Not Updated Try again',
            'data' => $id
             );
           $this->response($response, REST_Controller::HTTP_OK);
       } catch (Exception $ex) {
             throw new Exception('Sales_item controller_name : Error in remove_post function - ' . $ex);
        }  
  }
 }
