<?php 
/*
    Generated by Manuigniter v2.0 
    www.manuigniter.com
*/
use Restserver\Libraries\REST_Controller;
defined('BASEPATH') OR exit('No direct script access allowed');
require APPPATH . '/libraries/REST_Controller.php';
require APPPATH . 'libraries/Format.php';
class State extends REST_Controller{
 function __construct()
 {
       parent::__construct();
      $this->load->model('State_model');
 } 
 /*
* Listing of state
 */
public function get_all_post()
{
  try{
  $data['state'] = $this->State_model->get_all_state();
     if($data['state'] && $data['state']!=null){
       $state_ar = array();
       foreach($data['state'] as $s)
       {
       $s_ar = array();
       $s_ar['state_id'] = $s['state_id'];
       $s_ar['name'] = $s['name'];
       $s_ar['country_id'] = $s['country_id'];
       $state_ar[] = $s_ar;
       }
       $response = array(
       'status' => 200,
       'message' => 'get all data Succesfully',
       'data' => $state_ar,
       );
       $this->response($response, REST_Controller::HTTP_OK);
     }
     else{
       $response = array(
      'status' => 400,
      'message' => 'Detail is not found'
        );
       $this->response($response, REST_Controller::HTTP_OK); 
        }
       } catch (Exception $ex) {
             throw new Exception('State controller_name : Error in get_all_post function - ' . $ex);
        }  
}
 /*
  * Adding a new state
  */
 function addnew_post()
 {  
  try{
      $params = array(
       'name'=> $this->input->post('name'),
       'country_id'=> $this->input->post('country_id'),
        );
       $this->load->library('upload');
       $this->load->library('form_validation');
       if(isset($_POST) && count($_POST) > 0)     
        {  
            $state_id= $this->State_model->add_state($params);
   $data['state'] = $this->State_model->get_state($state_id);
           $response = array(
            'status' => 200,
            'message' => 'Succesfully Added',
            'data' => $data
             );
           $this->response($response, REST_Controller::HTTP_OK);
        }
        else
        { 
           $response = array(
            'status' => 400,
            'message' => 'Not Added try again',
            'data' => ''
             );
           $this->response($response, REST_Controller::HTTP_OK);
        }
       } catch (Exception $ex) {
             throw new Exception('State controller_name : Error in new state function - ' . $ex);
       }  
 }  
  /*
  * Editing a state
 */
  function edit_post($state_id)
 {   
  try{
   $data['state'] = $this->State_model->get_state($state_id);
       $this->load->library('upload');
       $this->load->library('form_validation');
     if(isset($data['state']['state_id']))
      {
        $params = array(
           'name'=> $this->input->post('name'),
           'country_id'=> $this->input->post('country_id'),
        );
          if(isset($_POST) && count($_POST) > 0)     
           {  
           $this->State_model->update_state($state_id,$params);
           $response = array(
            'status' => 200,
            'message' => 'Succesfully Updated',
            'data' => $state_id
             );
           $this->response($response, REST_Controller::HTTP_OK);
           }
           else
          {
           $response = array(
            'status' => 400,
            'message' => 'Not Updated Try again',
            'data' => $state_id
             );
           $this->response($response, REST_Controller::HTTP_OK);
          }
  }
       } catch (Exception $ex) {
             throw new Exception('State controller_name : Error in edit_post function - ' . $ex);
        }  
} 
/*
  * Deleting state
  */
  function remove_post($state_id)
   {
  try{
      $state = $this->State_model->get_state($state_id);
  // check if the state exists before trying to delete it
       if(isset($state['state_id']))
       {
         $this->State_model->delete_state($state_id);
           $response = array(
            'status' => 200,
            'message' => 'Succesfully Removed',
            'data' => $state_id
             );
           $this->response($response, REST_Controller::HTTP_OK);
       }
       else
           $response = array(
            'status' => 400,
            'message' => 'Not Updated Try again',
            'data' => $state_id
             );
           $this->response($response, REST_Controller::HTTP_OK);
       } catch (Exception $ex) {
             throw new Exception('State controller_name : Error in remove_post function - ' . $ex);
        }  
  }
 }
