<?php 
/*
    Generated by Manuigniter v2.0 
    www.manuigniter.com
*/
use Restserver\Libraries\REST_Controller;
defined('BASEPATH') OR exit('No direct script access allowed');
require APPPATH . '/libraries/REST_Controller.php';
require APPPATH . 'libraries/Format.php';
class Unit extends REST_Controller{
 function __construct()
 {
       parent::__construct();
      $this->load->model('Unit_model');
 } 
 /*
* Listing of unit
 */
public function get_all_post()
{
  try{
  $data['unit'] = $this->Unit_model->get_all_unit();
     if($data['unit'] && $data['unit']!=null){
       $unit_ar = array();
       foreach($data['unit'] as $u)
       {
       $u_ar = array();
       $u_ar['id'] = $u['id'];
       $u_ar['name'] = $u['name'];
       $unit_ar[] = $u_ar;
       }
       $response = array(
       'status' => 200,
       'message' => 'get all data Succesfully',
       'data' => $unit_ar,
       );
       $this->response($response, REST_Controller::HTTP_OK);
     }
     else{
       $response = array(
      'status' => 400,
      'message' => 'Detail is not found'
        );
       $this->response($response, REST_Controller::HTTP_OK); 
        }
       } catch (Exception $ex) {
             throw new Exception('Unit controller_name : Error in get_all_post function - ' . $ex);
        }  
}
 /*
  * Adding a new unit
  */
 function addnew_post()
 {  
  try{
      $params = array(
       'name'=> $this->input->post('name'),
        );
       $this->load->library('upload');
       $this->load->library('form_validation');
       if(isset($_POST) && count($_POST) > 0)     
        {  
            $id= $this->Unit_model->add_unit($params);
   $data['unit'] = $this->Unit_model->get_unit($id);
           $response = array(
            'status' => 200,
            'message' => 'Succesfully Added',
            'data' => $data
             );
           $this->response($response, REST_Controller::HTTP_OK);
        }
        else
        { 
           $response = array(
            'status' => 400,
            'message' => 'Not Added try again',
            'data' => ''
             );
           $this->response($response, REST_Controller::HTTP_OK);
        }
       } catch (Exception $ex) {
             throw new Exception('Unit controller_name : Error in new unit function - ' . $ex);
       }  
 }  
  /*
  * Editing a unit
 */
  function edit_post($id)
 {   
  try{
   $data['unit'] = $this->Unit_model->get_unit($id);
       $this->load->library('upload');
       $this->load->library('form_validation');
     if(isset($data['unit']['id']))
      {
        $params = array(
           'name'=> $this->input->post('name'),
        );
          if(isset($_POST) && count($_POST) > 0)     
           {  
           $this->Unit_model->update_unit($id,$params);
           $response = array(
            'status' => 200,
            'message' => 'Succesfully Updated',
            'data' => $id
             );
           $this->response($response, REST_Controller::HTTP_OK);
           }
           else
          {
           $response = array(
            'status' => 400,
            'message' => 'Not Updated Try again',
            'data' => $id
             );
           $this->response($response, REST_Controller::HTTP_OK);
          }
  }
       } catch (Exception $ex) {
             throw new Exception('Unit controller_name : Error in edit_post function - ' . $ex);
        }  
} 
/*
  * Deleting unit
  */
  function remove_post($id)
   {
  try{
      $unit = $this->Unit_model->get_unit($id);
  // check if the unit exists before trying to delete it
       if(isset($unit['id']))
       {
         $this->Unit_model->delete_unit($id);
           $response = array(
            'status' => 200,
            'message' => 'Succesfully Removed',
            'data' => $id
             );
           $this->response($response, REST_Controller::HTTP_OK);
       }
       else
           $response = array(
            'status' => 400,
            'message' => 'Not Updated Try again',
            'data' => $id
             );
           $this->response($response, REST_Controller::HTTP_OK);
       } catch (Exception $ex) {
             throw new Exception('Unit controller_name : Error in remove_post function - ' . $ex);
        }  
  }
 }
